ipranges:
  - domain:
      name: googlevideo.com
      url: 'https://<ip>/videoplayback?mn=NO-ID'
      response:
        headers:
          Server: gvs 1.0
      ranges: 
      - 216.21.170.207-216.21.170.210
