ipranges:
  - domain:
      name: youtube.com
      url: 'https://<ip>/get_video_info\?\&video_id\=\<NOID\>\&el\=info\&ps\=default\&eurl\=\&gl\=US\&hl\=e'
      response:
        headers:
          Server: YouTubeFrontEnd
      ranges: 
      - 216.58.211.206-216.58.211.210
