ipranges:
  - domain:
      name: googlevideo.com
      url: 'https://<ip>/videoplayback?mn=NO-ID'
      response:
        headers:
          Server: gvs 1.0
      ranges: 
      # Extracted from:
      # nslookup -q=TXT _netblocks.google.com 8.8.8.8
      # nslookup -q=TXT _netblocks3.google.com 8.8.8.8
      - 64.18.0.0/20
      - 64.233.160.0/19
      - 66.102.0.0/20
      - 66.249.80.0/20
      - 72.14.192.0/18
      - 74.125.0.0/16
      - 108.177.8.0/21
      - 173.194.0.0/16
      - 207.126.144.0/20
      - 209.85.128.0/17
      - 216.58.192.0/19
      - 216.239.32.0/19
      - 172.217.0.0/19
      - 108.177.96.0/19
